In [15]:
import numpy as np
x = [150, 200, 300, 450]
x
y=np.array(x)
type(x)

list

In [16]:
print(type(x))

<class 'list'>


In [17]:
type(y)

numpy.ndarray

In [18]:
y * 3

array([ 450,  600,  900, 1350])

In [19]:
#subsetting and slicing

In [20]:
y[3]

450

In [21]:
y[0:3]

array([150, 200, 300])

In [22]:
y[-1]

450

In [23]:
y > 200

array([False, False,  True,  True])

In [24]:
y != 200

array([ True, False,  True,  True])

In [25]:
y[y > 200]

array([300, 450])

In [26]:
y[y != 200]

array([150, 300, 450])

In [34]:
x = [list(range(0,6)), list(range(9,15)), list(range(20,26))]
x

[[0, 1, 2, 3, 4, 5], [9, 10, 11, 12, 13, 14], [20, 21, 22, 23, 24, 25]]

In [35]:
xnp = np.array(x)

In [36]:
x[0]

[0, 1, 2, 3, 4, 5]

In [37]:
x[0][1]

1

In [38]:
x[0][-1]

5

In [39]:
xnp[1, 3:5]

array([12, 13])

In [40]:
xnp > 10

array([[False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [41]:
xnp[:, 2]

array([ 2, 11, 22])

In [42]:
xnp[:, 2] > 10

array([False,  True,  True])

In [43]:
xnp[:, 2] [xnp[:, 2] > 10]

array([11, 22])

In [44]:
xnp[:, 2]

array([ 2, 11, 22])